### ISSUE TITLE
How to receive and inbox for which no token or authentication is needed?

### ISSUE THREAD

**Issue by phochste** [ErfgoedPod/evno#12]
E.g. in development mode (or a world readable inbox) I don't need a token. 

Evno crashes with

```
$ node dist/cli.js receive http://localhost:3000/service/inbox/
  _____                 _   _   _       _   _  __ _           _   _
 | ____|_   _____ _ __ | |_| \ | | ___ | |_(_)/ _(_) ___ __ _| |_(_) ___  _ __  ___
 |  _| \ \ / / _ \ '_ \| __|  \| |/ _ \| __| | |_| |/ __/ _` | __| |/ _ \| '_ \/ __|
 | |___ \ V /  __/ | | | |_| |\  | (_) | |_| |  _| | (_| (_| | |_| | (_) | | | \__ \
 |_____| \_/ \___|_| |_|\__|_| \_|\___/ \__|_|_| |_|\___\__,_|\__|_|\___/|_| |_|___/

node:fs:723
  handleErrorFromBinding(ctx);
  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Module.readFileSync (node:fs:479:19)
    at Function.<anonymous> (file:///Users/hochsten/github.com/ErfgoedPod/evno/dist/receiver.js:46:43)
    at Generator.next (<anonymous>)
    at /Users/hochsten/github.com/ErfgoedPod/evno/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/tslib/tslib.js:114:16)
    at Function.build (file:///Users/hochsten/github.com/ErfgoedPod/evno/dist/receiver.js:42:16)
    at file:///Users/hochsten/github.com/ErfgoedPod/evno/dist/cli.js:46:37 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

**Comment by phochste** [comment]
Probably because the commandline sets a default tokenLocation...

**Comment by phochste** [comment]
Nope..it is something deeper. @mielvds how do you test this on your local solid pod?

**Comment by mielvds** [comment]
It's something with reading/writing the cache directory. Do you provide a cache path or have a .cache folder?

**Comment by phochste** [comment]
Ja that is available. It tried to read the token which is not there. But when I remove that part from the code, then it tries to generate a token from the CSS which is not working, because the development CSS doesn't do authentication.

**Comment by mielvds** [comment]
The problem was that the default token location was a directory, which cannot be written like a file ofc. I put in a safeguard in be724f8.
